name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run linter
        run: |
          export PYTHONPATH=$(pwd)
          pylint **/*.py --ignore-paths=__tests__

  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install pytest
        run: |
          pip install pytest pytest-flask

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pylint **/*.py --ignore-paths=__tests__

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Deploy
        run: |
          export PYTHONPATH=$(pwd) 
          python -m flask run --port 3001 --host 0.0.0.0 > output.log 2>&1 &